// Nasdaq-100 companies (static list)
export const NASDAQ_100 = [
  { ticker: "AAPL", name: "Apple Inc." },
  { ticker: "MSFT", name: "Microsoft Corporation" },
  { ticker: "AMZN", name: "Amazon.com Inc." },
  { ticker: "NVDA", name: "NVIDIA Corporation" },
  { ticker: "GOOGL", name: "Alphabet Inc." },
  { ticker: "GOOG", name: "Alphabet Inc." },
  { ticker: "META", name: "Meta Platforms Inc." },
  { ticker: "TSLA", name: "Tesla Inc." },
  { ticker: "AVGO", name: "Broadcom Inc." },
  { ticker: "ASML", name: "ASML Holding N.V." },
  { ticker: "AMD", name: "Advanced Micro Devices Inc." },
  { ticker: "MU", name: "Micron Technology Inc." },
  { ticker: "ADBE", name: "Adobe Inc." },
  { ticker: "NFLX", name: "Netflix Inc." },
  { ticker: "QCOM", name: "Qualcomm Inc." },
  { ticker: "INTC", name: "Intel Corporation" },
  { ticker: "INTU", name: "Intuit Inc." },
  { ticker: "CSCO", name: "Cisco Systems Inc." },
  { ticker: "SNPS", name: "Synopsys Inc." },
  { ticker: "CDNS", name: "Cadence Design Systems Inc." },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc." },
  { ticker: "PAYX", name: "Paychex Inc." },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc." },
  { ticker: "ANSS", name: "ANSYS Inc." },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals Inc." },
  { ticker: "CTSH", name: "Cognizant Technology Solutions Corporation" },
  { ticker: "DLTR", name: "Dollar Tree Inc." },
  { ticker: "ILMN", name: "Illumina Inc." },
  { ticker: "IDXX", name: "IDEXX Laboratories Inc." },
  { ticker: "MRVL", name: "Marvell Technology Inc." },
  { ticker: "MRNA", name: "Moderna Inc." },
  { ticker: "LCID", name: "Lucid Group Inc." },
  { ticker: "ABNB", name: "Airbnb Inc." },
  { ticker: "DOCU", name: "DocuSign Inc." },
  { ticker: "DDOG", name: "Datadog Inc." },
  { ticker: "OKTA", name: "Okta Inc." },
  { ticker: "WDAY", name: "Workday Inc." },
  { ticker: "ZM", name: "Zoom Video Communications Inc." },
  { ticker: "SNOW", name: "Snowflake Inc." },
  { ticker: "TWLO", name: "Twilio Inc." },
  { ticker: "DXCM", name: "DexCom Inc." },
  { ticker: "FTNT", name: "Fortinet Inc." },
  { ticker: "PSTG", name: "Pure Storage Inc." },
  { ticker: "TTD", name: "The Trade Desk Inc." },
  { ticker: "MCHP", name: "Microchip Technology Inc." },
  { ticker: "ADSK", name: "Autodesk Inc." },
  { ticker: "VERX", name: "Verisk Analytics Inc." },
  { ticker: "AMAT", name: "Applied Materials Inc." },
  { ticker: "LRCX", name: "Lam Research Corporation" },
  { ticker: "KLAC", name: "KLA Corporation" },
  { ticker: "SPLK", name: "Splunk Inc." },
  { ticker: "NKTR", name: "Nektar Therapeutics Inc." },
  { ticker: "ULVR", name: "Unilever PLC" },
  { ticker: "SGEN", name: "Seagen Inc." },
  { ticker: "CHTR", name: "Charter Communications Inc." },
  { ticker: "ATVI", name: "Activision Blizzard Inc." },
  { ticker: "XEL", name: "Xcel Energy Inc." },
  { ticker: "XLNX", name: "Xilinx Inc." },
  { ticker: "ISRG", name: "Intuitive Surgical Inc." },
  { ticker: "BIIB", name: "Biogen Inc." },
  { ticker: "SIRI", name: "Sirius XM Holdings Inc." },
  { ticker: "VRSK", name: "Verisk Analytics Inc." },
  { ticker: "CPRT", name: "Carpetright PLC" },
  { ticker: "ALXO", name: "Alexion Pharmaceuticals Inc." },
  { ticker: "BKNG", name: "Booking Holdings Inc." },
  { ticker: "PCAR", name: "PACCAR Inc." },
  { ticker: "PANW", name: "Palo Alto Networks Inc." },
  { ticker: "MNST", name: "Monster Beverage Corporation" },
  { ticker: "NTES", name: "NetEase Inc." },
  { ticker: "PYPL", name: "PayPal Holdings Inc." },
  { ticker: "RGEN", name: "Ragenesis Inc." },
  { ticker: "EBAY", name: "eBay Inc." },
  { ticker: "FAST", name: "Fastenal Company" },
  { ticker: "GRMN", name: "Garmin Ltd." },
  { ticker: "HON", name: "Honeywell International Inc." },
  { ticker: "ADI", name: "Analog Devices Inc." },
  { ticker: "ACGL", name: "Arch Capital Group Ltd." },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals Inc." },
  { ticker: "AZPN", name: "Aspen Aerogels Inc." },
  { ticker: "AKAM", name: "Akamai Technologies Inc." },
  { ticker: "ALRM", name: "Alarm.com Holdings Inc." },
  { ticker: "ALEX", name: "Alexander & Baldwin Inc." },
  { ticker: "AMBA", name: "Ambarella Inc." },
  { ticker: "AMGN", name: "Amgen Inc." },
  { ticker: "APPF", name: "AppFolio Inc." },
  { ticker: "ARUN", name: "Arun Inc." },
  { ticker: "ASPS", name: "Aspirity Inc." },
  { ticker: "ATLI", name: "Atlanticus Holdings Corporation" },
  { ticker: "AURE", name: "Aurelius Minerals Inc." },
  { ticker: "AVNT", name: "Avnet Inc." },
  { ticker: "AWAY", name: "Away Inc." },
  { ticker: "AXTI", name: "AXT Inc." },
  { ticker: "BCED", name: "BCE Inc." },
  { ticker: "BBGI", name: "BB Global Inc." },
  { ticker: "BCLI", name: "Bioanalytical Systems Inc." },
]
