import type {Metadata} from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import {Providers} from "@/app/providers";
import React from "react";

const inter = Inter({subsets: ["latin"], variable: "--font-sans", display: "swap"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.variable}>
        <Providers>
            <body>
            {children}
            </body>
        </Providers>
        </html>
    );
}
