name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 25.2.1
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test
      continue-on-error: true  # Remove if you want the build to fail on test error
